appname = API_MID_SPY
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

CRUD_SPY = http://localhost:8081/v1/

# --- PayPal config ---
paypal_client_id = AQvAF1VdHXee7eTPVYy515ni8mkeB698nAP3vom3ZBuBLTHEaci2e9ySj1_HMFniutieNbi-8Y0RRxCi
paypal_secret = EE-O2r2HMVK_SpLej1R5xFjZ3lkVMfiaeIkip3m01PWe3Pa57dyHFUhycDMEdz1L4Kd9y0Eca7UkcpXV
paypal_api_base = https://api-m.sandbox.paypal.com

# GetOne para consulta individual de usuarios http://localhost:8081/v1/Usuarios?query=Email:camilo@gmail.com

# link del post http://localhost:8082/v1/"nombre del servicio"
# formato del body post para usuarios
# {
#     "Nombres": "ABC",
#     "Apellidos": "ABC",
#     "NumeroIdentificacionUsuarios": "123...",
#     "Email": "ABC@...",
#     "Telefono": 123...,
#     "IdContrasenaFk": {
#     "Id": #},
#     "Estado": true/false,
#     "IdRolesFk": {
#     "Id": #,
#     "Nombre": "CARGO"},
#     "Imagen": "URL"
# }

# link del getall http://localhost:8082/v1/"nombre del servicio"
# link del getone http://localhost:8082/v1/"nombre del servicio"/#
# link del put http://localhost:8082/v1/"nombre de servicio"/#
# formato del body put para usuarios
# {
#     "Nombres": "ABC",
#     "Apellidos": "ABC",
#     "NumeroIdentificacionUsuarios": "123...",
#     "Email": "ABC@...",
#     "Telefono": 123...,
#     "IdContrasenaFk": {
#     "Id": #},
#     "Estado": true/false,
#     "IdRolesFk": {
#     "Id": #,
#     "Nombre": "CARGO"},
#     "Imagen": "URL"
# }

