appname = API_MID_SPY
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

CRUD_SPY = http://localhost:8081/v1/

# formato del body post para usuarios
# {
#     "Apellidos": "ABC",
#     "Direccion": "CLL12#",
#     "Edad": #,
#     "Email": "ABC@...",
#     "IdRolesFk": {
#     "Id": #,
#     "Nombre": "CARGO"},
#     "Nombres": "ABC",
#     "NumeroIdentificacionUsuarios": "123...",
#     "Telefono": 123...,
#     "IdContrasenaFk": {
#     "Id": #},
#     "FechaNacimiento": "YYYY/MM/DD HH:MM:SS"
# }

# link del getone http://localhost:8082/v1/usuarios/#

# link del getall http://localhost:8082/v1/"nombre del controlador del crud"

# formato del body put para usuarios
# {
#     "Apellidos": "ABC",
#     "Direccion": "CLL12#",
#     "Edad": #,
#     "Email": "ABC@...",
#     "IdRolesFk": {
#     "Id": #,
#     "Nombre": "CARGO"},
#     "Nombres": "ABC",
#     "NumeroIdentificacionUsuarios": "123...",
#     "Telefono": 123...,
#     "IdContrasenaFk": {
#     "Id": #},
#     "FechaNacimiento": "YYYY/MM/DD HH:MM:SS"
#     "Estado": true/false,
# }

